version: "3.3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "5353:5353"
      - "8324:8324/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
    hostname: plex.achorprod.com
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - ADVERTISE_IP=https://plex.anchorprod.com/
      - TZ=EST
      - PLEX_CLAIM=claim-X_zVEpsEt6Y-kNfUFa_s
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/jarrett/plex/plex/data:/config
      - /media/plex/tv:/tv
      - /media/plex/movies:/movies
    restart: unless-stopped
    cpus: "12.0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.plex.entrypoints=web,websecure"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.plex.tls=true"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - /home/jarrett/plex/sonarr/data:/config
      - /media/plex/tv:/tv
      - /media/sab/downloads:/downloads 
      - /media/plex/sab/incomplete:/incomplete
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=web, websecure"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
#      - "traefik.http.routers.sonarr.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.sonarr.tls=true"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - /home/jarrett/plex/radarr/data:/config
      - /media/plex/movies:/movies #optional
      - /media/sab/downloads:/downloads 
      - /media/plex/sab/incomplete:/incomplete
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.entrypoints=web, websecure"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
#      - "traefik.http.routers.radarr.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.radarr.tls=true"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sab.anchorprod.com
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - /home/jarrett/plex/sab/data:/config
      - /media/plex/sab/downloads:/downloads #optional
      - /media/plex/sab/incomplete:/incomplete #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sabnzbd.tls=true"

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=EST
    ports:
      - 5055:5055
    volumes:
      - /home/jarrett/plex/over/data:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.overseerr.entrypoints=web, websecure"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certresolver=mytlschallenge"    

networks:
  default:
    name: traefik_default
    external: true          